// <auto-generated />
using System;
using Dashboard_v2.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard_v2.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502163532_AuthorSearchKeys")]
    partial class AuthorSearchKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AreaDelConocimientoLineaDeInvestigacion", b =>
                {
                    b.Property<string>("AreaDelConocimientoId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("LineaDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("AreaDelConocimientoId", "LineaDeInvestigacionId");

                    b.HasIndex("LineaDeInvestigacionId");

                    b.ToTable("AreasDelConocimientoLineasDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("AreaInvestigaAreaDelConocimiento", b =>
                {
                    b.Property<string>("AreaId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaDelConocimientoId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("AreaId", "AreaDelConocimientoId");

                    b.HasIndex("AreaDelConocimientoId");

                    b.ToTable("AreasInvestiganAreasDelConocimiento", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UniversidadId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AreaDelConocimiento", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("AreasDelConocimiento", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Author", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FirstNameKey")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("LastNameKey")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Authors_UserId_Unique")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPresentation", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("PresentationId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorId", "PresentationId");

                    b.HasIndex("PresentationId");

                    b.ToTable("AuthorPresentations", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPublication", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("AuthorId", "PublicationId");

                    b.HasIndex("PublicationId");

                    b.ToTable("AuthorPublications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AwardTypeId");

                    b.ToTable("Awards", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AwardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AwardTypes", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Clasificacion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Clasificaciones", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RedId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("RedId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CreadorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreadorId");

                    b.ToTable("GruposDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.GrupoEstudiantil", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("GruposEstudiantiles", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.IndexedPublication", b =>
                {
                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.HasKey("PublicationId");

                    b.ToTable("IndexedPublications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Institution", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Institutions", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalGroup1Publication", b =>
                {
                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Cuartil")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("PublicationId");

                    b.ToTable("JournalGroup1Publications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalPublication", b =>
                {
                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DataBase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.HasKey("PublicationId");

                    b.ToTable("JournalPublications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.LineaDeInvestigacion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("LineasDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Norma", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Normas", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Patente", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<bool>("EsNacional")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroSolicitudConcesion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Patentes", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Presentations", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProductoComercializado", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("TipoProductoComercializadoId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("TipoProductoComercializadoId");

                    b.ToTable("ProductosComercializados", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Proyecto", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("CantidadEstudiantes")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadEstudiantesContratados")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadMiembrosUH")
                        .HasColumnType("integer");

                    b.Property<string>("ClasificacionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("JefeId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("NumeroMiembros")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TributaFormacionDoctoral")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClasificacionId");

                    b.HasIndex("JefeId");

                    b.ToTable("Proyectos", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Publication", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NormalizedTitle")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUrlDoi")
                        .HasColumnType("text");

                    b.Property<string>("ProyectoId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PublicationData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublicationType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UrlDoi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Publications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Red", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("CantidadProfesores")
                        .HasColumnType("integer");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Reds", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.RedCoordinada", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CoordinadorId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("RedId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CoordinadorId");

                    b.HasIndex("RedId", "AreaId")
                        .IsUnique();

                    b.ToTable("RedesCoordinadas", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Registro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsInformatico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<string>("NumeroCertificado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Registros", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "OwnerId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.TipoProductoComercializado", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("TipoProductosComercializados", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Universidad", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Universidades", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("InvestigationCategory")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTrained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("ScientificCategory")
                        .HasColumnType("integer");

                    b.Property<int>("TeachingCategory")
                        .HasColumnType("integer");

                    b.Property<string>("UserLastName1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserLastName2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserAwarded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAwardeds", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Role");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("EventInstitution", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("InstitutionId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("EventId", "InstitutionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("EventsInstitutions", (string)null);
                });

            modelBuilder.Entity("GrupoDeInvestigacionLineaDeInvestigacion", b =>
                {
                    b.Property<string>("GrupoDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("LineaDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("GrupoDeInvestigacionId", "LineaDeInvestigacionId");

                    b.HasIndex("LineaDeInvestigacionId");

                    b.ToTable("GruposDeInvestigacionLineasDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("GrupoDeInvestigacionUsuario", b =>
                {
                    b.Property<string>("GrupoDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("GrupoDeInvestigacionId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GruposDeInvestigacionUsuarios", (string)null);
                });

            modelBuilder.Entity("GrupoEstudiantilLineaDeInvestigacion", b =>
                {
                    b.Property<string>("GrupoEstudiantilId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("LineaDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("GrupoEstudiantilId", "LineaDeInvestigacionId");

                    b.HasIndex("LineaDeInvestigacionId");

                    b.ToTable("GruposEstudiantilesLineasDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("RedUsuario", b =>
                {
                    b.Property<string>("RedId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("RedId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RedsUsuarios", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.Proyecto");

                    b.Property<string>("CodigoProyecto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContribucionEjesEstrategicos")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ContribucionSectoresEstrategicos")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EntidadEjecutoraParticipante")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EntidadEjecutoraPrincipal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EstadoDeEjecucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<bool>("TributaDesarrolloLocal")
                        .HasColumnType("boolean");

                    b.ToTable("ProyectosEnEjecucion", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoEnRevision", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.Proyecto");

                    b.Property<string>("Situacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("ProyectosEnRevision", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoApoyoPrograma", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion");

                    b.Property<string>("NombrePrograma")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("TipoPAP")
                        .HasColumnType("integer");

                    b.ToTable("ProyectosApoyoPrograma", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoColabInternacional", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion");

                    b.Property<string>("FuenteFinanciacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("TerminosReferencia")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.ToTable("ProyectosColaboracionInternacional", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoDesarrolloLocal", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("ProyectosDesarrolloLocal", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoEmpresarial", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.ToTable("ProyectosEmpresariales", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoNoEmpresarial", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion");

                    b.Property<string>("EntidadNoEmpresarial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.ToTable("ProyectosNoEmpresariales", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoPNAP", b =>
                {
                    b.HasBaseType("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion");

                    b.Property<string>("FinanciamientoUH")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.ToTable("ProyectosPNAP", (string)null);
                });

            modelBuilder.Entity("AreaDelConocimientoLineaDeInvestigacion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.AreaDelConocimiento", null)
                        .WithMany()
                        .HasForeignKey("AreaDelConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.LineaDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("LineaDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AreaInvestigaAreaDelConocimiento", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.AreaDelConocimiento", null)
                        .WithMany()
                        .HasForeignKey("AreaDelConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Area", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Universidad", "Universidad")
                        .WithMany("Areas")
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Author", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.User", "User")
                        .WithOne("AuthorProfile")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.Author", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPresentation", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Author", "Author")
                        .WithMany("AuthorPresentations")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Presentation", "Presentation")
                        .WithMany("AuthorPresentations")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPublication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Author", "Author")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Publication", "Publication")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Award", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.AwardType", "AwardType")
                        .WithMany("Awards")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Event", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Country", "Country")
                        .WithMany("Events")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Red", "Red")
                        .WithMany("Events")
                        .HasForeignKey("RedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("EventType");

                    b.Navigation("Red");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Area", "Area")
                        .WithMany("GruposDeInvestigacion")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.GrupoEstudiantil", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.IndexedPublication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Publication", "Publication")
                        .WithOne("IndexedPublication")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.IndexedPublication", "PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalGroup1Publication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.JournalPublication", "JournalPublication")
                        .WithOne("JournalGroup1Publication")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.JournalGroup1Publication", "PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalPublication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalPublication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Publication", "Publication")
                        .WithOne("JournalPublication")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.JournalPublication", "PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Norma", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Institution", "Institution")
                        .WithMany("Normas")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Presentation", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Event", "Event")
                        .WithMany("Presentations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProductoComercializado", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Institution", "Institution")
                        .WithMany("ProductosComercializados")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.TipoProductoComercializado", "TipoProductoComercializado")
                        .WithMany("Productos")
                        .HasForeignKey("TipoProductoComercializadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("TipoProductoComercializado");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Proyecto", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Clasificacion", "Clasificacion")
                        .WithMany("Proyectos")
                        .HasForeignKey("ClasificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", "JefeUsuario")
                        .WithMany("ProyectosComoJefe")
                        .HasForeignKey("JefeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clasificacion");

                    b.Navigation("JefeUsuario");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Publication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("PublicacionesDerivadas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Red", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Country", "Country")
                        .WithMany("Reds")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.RedCoordinada", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Area", "Area")
                        .WithMany("RedesCoordinadas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", "Coordinador")
                        .WithMany("RedesCoordinadas")
                        .HasForeignKey("CoordinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Red", "Red")
                        .WithMany("RedesCoordinadas")
                        .HasForeignKey("RedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Coordinador");

                    b.Navigation("Red");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Registro", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Country", "Country")
                        .WithMany("Registros")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Institution", "Institution")
                        .WithMany("Registros")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Resource", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.User", "Owner")
                        .WithMany("OwnedResources")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.User", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Area", "Area")
                        .WithMany("Users")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserAwarded", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Award", "Award")
                        .WithMany("UserAwardeds")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventInstitution", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Institution", null)
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoDeInvestigacionLineaDeInvestigacion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("GrupoDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.LineaDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("LineaDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoDeInvestigacionUsuario", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("GrupoDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoEstudiantilLineaDeInvestigacion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.GrupoEstudiantil", null)
                        .WithMany()
                        .HasForeignKey("GrupoEstudiantilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.LineaDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("LineaDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RedUsuario", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Red", null)
                        .WithMany()
                        .HasForeignKey("RedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Proyecto", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoEnRevision", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Proyecto", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoEnRevision", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoApoyoPrograma", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoApoyoPrograma", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoColabInternacional", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoColabInternacional", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoDesarrolloLocal", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoDesarrolloLocal", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoEmpresarial", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoEmpresarial", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoNoEmpresarial", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoNoEmpresarial", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.ProyectoPNAP", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.ProyectoEnEjecucion", null)
                        .WithOne()
                        .HasForeignKey("Dashboard_v2.Domain.Entities.ProyectoPNAP", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Area", b =>
                {
                    b.Navigation("GruposDeInvestigacion");

                    b.Navigation("RedesCoordinadas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Author", b =>
                {
                    b.Navigation("AuthorPresentations");

                    b.Navigation("AuthorPublications");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Award", b =>
                {
                    b.Navigation("UserAwardeds");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AwardType", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Clasificacion", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Country", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Reds");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Event", b =>
                {
                    b.Navigation("Presentations");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Institution", b =>
                {
                    b.Navigation("Normas");

                    b.Navigation("ProductosComercializados");

                    b.Navigation("Registros");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalPublication", b =>
                {
                    b.Navigation("JournalGroup1Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Presentation", b =>
                {
                    b.Navigation("AuthorPresentations");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Proyecto", b =>
                {
                    b.Navigation("PublicacionesDerivadas");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Publication", b =>
                {
                    b.Navigation("AuthorPublications");

                    b.Navigation("IndexedPublication");

                    b.Navigation("JournalPublication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Red", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("RedesCoordinadas");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.TipoProductoComercializado", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Universidad", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthorProfile");

                    b.Navigation("OwnedResources");

                    b.Navigation("ProyectosComoJefe");

                    b.Navigation("RedesCoordinadas");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
