// <auto-generated />
using System;
using System.Collections.Generic;
using Dashboard_v2.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dashboard_v2.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408025936_AddCreadorIdToGrupo")]
    partial class AddCreadorIdToGrupo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AreaDelConocimientoLineaDeInvestigacion", b =>
                {
                    b.Property<string>("AreaDelConocimientoId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("LineaDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("AreaDelConocimientoId", "LineaDeInvestigacionId");

                    b.HasIndex("LineaDeInvestigacionId");

                    b.ToTable("AreasDelConocimientoLineasDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("AreaInvestigaAreaDelConocimiento", b =>
                {
                    b.Property<string>("AreaId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaDelConocimientoId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("AreaId", "AreaDelConocimientoId");

                    b.HasIndex("AreaDelConocimientoId");

                    b.ToTable("AreasInvestiganAreasDelConocimiento", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Area", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UniversidadId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UniversidadId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AreaDelConocimiento", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("AreasDelConocimiento", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Author", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Authors_UserId_Unique")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Authors", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPresentation", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("PresentationId")
                        .HasColumnType("integer");

                    b.HasKey("AuthorId", "PresentationId");

                    b.HasIndex("PresentationId");

                    b.ToTable("AuthorPresentations", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPublication", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("AuthorId", "PublicationId");

                    b.HasIndex("PublicationId");

                    b.ToTable("AuthorPublications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AwardTypeId");

                    b.ToTable("Awards", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AwardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("AwardTypes", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Institutions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("EventTypeId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CreadorId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreadorId");

                    b.ToTable("GruposDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.IndexedPublication", b =>
                {
                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PublicationId");

                    b.ToTable("IndexedPublications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalGroup1Publication", b =>
                {
                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Cuartil")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("PublicationId");

                    b.ToTable("JournalGroup1Publications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalPublication", b =>
                {
                    b.Property<string>("PublicationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("DataBase")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Group")
                        .HasColumnType("integer");

                    b.HasKey("PublicationId");

                    b.ToTable("JournalPublications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.LineaDeInvestigacion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("LineasDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Presentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Presentations", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Publication", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PublicationData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublicationType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UrlDoi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publications", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Type");

                    b.HasIndex("Type", "OwnerId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Universidad", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Universidades", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("InvestigationCategory")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTrained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<int>("ScientificCategory")
                        .HasColumnType("integer");

                    b.Property<int>("TeachingCategory")
                        .HasColumnType("integer");

                    b.Property<string>("UserLastName1")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserLastName2")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserAwarded", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwardId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAwardeds", (string)null);
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "Role");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("GrupoDeInvestigacionLineaDeInvestigacion", b =>
                {
                    b.Property<string>("GrupoDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("LineaDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("GrupoDeInvestigacionId", "LineaDeInvestigacionId");

                    b.HasIndex("LineaDeInvestigacionId");

                    b.ToTable("GruposDeInvestigacionLineasDeInvestigacion", (string)null);
                });

            modelBuilder.Entity("GrupoDeInvestigacionUsuario", b =>
                {
                    b.Property<string>("GrupoDeInvestigacionId")
                        .HasColumnType("character varying(450)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("character varying(450)");

                    b.HasKey("GrupoDeInvestigacionId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("GruposDeInvestigacionUsuarios", (string)null);
                });

            modelBuilder.Entity("AreaDelConocimientoLineaDeInvestigacion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.AreaDelConocimiento", null)
                        .WithMany()
                        .HasForeignKey("AreaDelConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.LineaDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("LineaDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AreaInvestigaAreaDelConocimiento", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.AreaDelConocimiento", null)
                        .WithMany()
                        .HasForeignKey("AreaDelConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Area", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Universidad", "Universidad")
                        .WithMany("Areas")
                        .HasForeignKey("UniversidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Universidad");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Author", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.User", "User")
                        .WithOne("AuthorProfile")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.Author", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPresentation", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Author", "Author")
                        .WithMany("AuthorPresentations")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Presentation", "Presentation")
                        .WithMany("AuthorPresentations")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Presentation");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AuthorPublication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Author", "Author")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.Publication", "Publication")
                        .WithMany("AuthorPublications")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Award", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.AwardType", "AwardType")
                        .WithMany("Awards")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwardType");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Event", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Country", "Country")
                        .WithMany("Events")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Area", "Area")
                        .WithMany("GruposDeInvestigacion")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Area");

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.IndexedPublication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Publication", "Publication")
                        .WithOne("IndexedPublication")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.IndexedPublication", "PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalGroup1Publication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.JournalPublication", "JournalPublication")
                        .WithOne("JournalGroup1Publication")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.JournalGroup1Publication", "PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JournalPublication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalPublication", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Publication", "Publication")
                        .WithOne("JournalPublication")
                        .HasForeignKey("Dashboard_v2.Domain.Entities.JournalPublication", "PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Presentation", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Event", "Event")
                        .WithMany("Presentations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Resource", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.User", "Owner")
                        .WithMany("OwnedResources")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserAwarded", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.Award", "Award")
                        .WithMany("UserAwardeds")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrupoDeInvestigacionLineaDeInvestigacion", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("GrupoDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.LineaDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("LineaDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GrupoDeInvestigacionUsuario", b =>
                {
                    b.HasOne("Dashboard_v2.Domain.Entities.GrupoDeInvestigacion", null)
                        .WithMany()
                        .HasForeignKey("GrupoDeInvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dashboard_v2.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Area", b =>
                {
                    b.Navigation("GruposDeInvestigacion");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Author", b =>
                {
                    b.Navigation("AuthorPresentations");

                    b.Navigation("AuthorPublications");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Award", b =>
                {
                    b.Navigation("UserAwardeds");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.AwardType", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Country", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Event", b =>
                {
                    b.Navigation("Presentations");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.JournalPublication", b =>
                {
                    b.Navigation("JournalGroup1Publication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Presentation", b =>
                {
                    b.Navigation("AuthorPresentations");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Publication", b =>
                {
                    b.Navigation("AuthorPublications");

                    b.Navigation("IndexedPublication");

                    b.Navigation("JournalPublication");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.Universidad", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("Dashboard_v2.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthorProfile");

                    b.Navigation("OwnedResources");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
